# Restore feature-rich corrupt HTML and repair U+FFFD Spanish accents.
# ASCII-only script source; accents via [char]0x....
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$indexPath = Join-Path (Split-Path -Parent $here) "index.html"
if (-not (Test-Path -LiteralPath $indexPath)) { throw "index.html not found at $indexPath" }
$corrupt = Join-Path $env:TEMP "index-corrupt.html"
if (-not (Test-Path $corrupt)) { throw "Missing corrupt backup: $corrupt" }

$t = [System.IO.File]::ReadAllText($corrupt, [System.Text.UTF8Encoding]::new($false))
$R = [char]0xFFFD
$ellipsis = [char]0x2026
$middot = [char]0x00B7
$endash = [char]0x2013

function U([int[]]$codes) {
  -join ($codes | ForEach-Object { [char]$_ })
}

$explicit = New-Object "System.Collections.Generic.Dictionary[string,string]"
function Add-Fix([string]$left, [string]$right, [string]$fixed) {
  $key = $left + $script:R + $right
  if (-not $script:explicit.ContainsKey($key)) { $script:explicit[$key] = $fixed }
}

Add-Fix "Tambi" "n" (U @(0x54,0x61,0x6D,0x62,0x69,0x00E9,0x6E))
Add-Fix "autom" "ticamente" ("autom" + [char]0x00E1 + "ticamente")
Add-Fix "ma" "ana" ("ma" + [char]0x00F1 + "ana")
Add-Fix "Ma" "ana" ("Ma" + [char]0x00F1 + "ana")
Add-Fix "d" "a" ("d" + [char]0x00ED + "a")
Add-Fix "D" "a" ("D" + [char]0x00ED + "a")
Add-Fix "d" "as" ("d" + [char]0x00ED + "as")
Add-Fix "Producci" "n" ("Producci" + [char]0x00F3 + "n")
Add-Fix "producci" "n" ("producci" + [char]0x00F3 + "n")
Add-Fix "Unificaci" "n" ("Unificaci" + [char]0x00F3 + "n")
Add-Fix "log" "stica" ("log" + [char]0x00ED + "stica")
Add-Fix "Sesi" "n" ("Sesi" + [char]0x00F3 + "n")
Add-Fix "men" "" ("men" + [char]0x00FA)
Add-Fix "Men" "" ("Men" + [char]0x00FA)
Add-Fix "cat" "logo" ("cat" + [char]0x00E1 + "logo")
Add-Fix "gr" "ficos" ("gr" + [char]0x00E1 + "ficos")
Add-Fix "A" "o" ("A" + [char]0x00F1 + "o")
Add-Fix "a" "o" ("a" + [char]0x00F1 + "o")
Add-Fix "a" "os" ("a" + [char]0x00F1 + "os")
Add-Fix "validaci" "n" ("validaci" + [char]0x00F3 + "n")
Add-Fix "Validaci" "n" ("Validaci" + [char]0x00F3 + "n")
Add-Fix "m" "dulo" ("m" + [char]0x00F3 + "dulo")
Add-Fix "M" "dulo" ("M" + [char]0x00F3 + "dulo")
Add-Fix "m" "dulos" ("m" + [char]0x00F3 + "dulos")
Add-Fix "M" "dulos" ("M" + [char]0x00F3 + "dulos")
Add-Fix "" "nicos" ([char]0x00FA + "nicos")
Add-Fix "" "nico" ([char]0x00FA + "nico")
Add-Fix "Paginaci" "n" ("Paginaci" + [char]0x00F3 + "n")
Add-Fix "p" "gina" ("p" + [char]0x00E1 + "gina")
Add-Fix "P" "gina" ("P" + [char]0x00E1 + "gina")
Add-Fix "" "ltima" ([char]0x00DA + "ltima")
Add-Fix "" "ltimo" ([char]0x00DA + "ltimo")
Add-Fix "" "ltimos" ([char]0x00FA + "ltimos")
Add-Fix "" "ltimas" ([char]0x00FA + "ltimas")
Add-Fix "Atr" "s" ("Atr" + [char]0x00E1 + "s")
Add-Fix "se" "ales" ("se" + [char]0x00F1 + "ales")
Add-Fix "se" "al" ("se" + [char]0x00F1 + "al")
Add-Fix "Se" "al" ("Se" + [char]0x00F1 + "al")
Add-Fix "m" "vil" ("m" + [char]0x00F3 + "vil")
Add-Fix "Gu" "as" ("Gu" + [char]0x00ED + "as")
Add-Fix "gu" "a" ("gu" + [char]0x00ED + "a")
Add-Fix "Gu" "a" ("Gu" + [char]0x00ED + "a")
Add-Fix "m" "s" ("m" + [char]0x00E1 + "s")
Add-Fix "M" "s" ("M" + [char]0x00E1 + "s")
Add-Fix "Despu" "s" ("Despu" + [char]0x00E9 + "s")
Add-Fix "despu" "s" ("despu" + [char]0x00E9 + "s")
Add-Fix "n" "mero" ("n" + [char]0x00FA + "mero")
Add-Fix "N" "mero" ("N" + [char]0x00FA + "mero")
Add-Fix "c" "digo" ("c" + [char]0x00F3 + "digo")
Add-Fix "C" "digo" ("C" + [char]0x00F3 + "digo")
Add-Fix "r" "pido" ("r" + [char]0x00E1 + "pido")
Add-Fix "r" "pida" ("r" + [char]0x00E1 + "pida")
Add-Fix "b" "squeda" ("b" + [char]0x00FA + "squeda")
Add-Fix "B" "squeda" ("B" + [char]0x00FA + "squeda")
Add-Fix "informaci" "n" ("informaci" + [char]0x00F3 + "n")
Add-Fix "descripci" "n" ("descripci" + [char]0x00F3 + "n")
Add-Fix "secci" "n" ("secci" + [char]0x00F3 + "n")
Add-Fix "opci" "n" ("opci" + [char]0x00F3 + "n")
Add-Fix "Opci" "n" ("Opci" + [char]0x00F3 + "n")
Add-Fix "acci" "n" ("acci" + [char]0x00F3 + "n")
Add-Fix "Acci" "n" ("Acci" + [char]0x00F3 + "n")
Add-Fix "revisi" "n" ("revisi" + [char]0x00F3 + "n")
Add-Fix "sincronizaci" "n" ("sincronizaci" + [char]0x00F3 + "n")
Add-Fix "Sincronizaci" "n" ("Sincronizaci" + [char]0x00F3 + "n")
Add-Fix "exportaci" "n" ("exportaci" + [char]0x00F3 + "n")
Add-Fix "navegaci" "n" ("navegaci" + [char]0x00F3 + "n")
Add-Fix "configuraci" "n" ("configuraci" + [char]0x00F3 + "n")
Add-Fix "operaci" "n" ("operaci" + [char]0x00F3 + "n")
Add-Fix "Operaci" "n" ("Operaci" + [char]0x00F3 + "n")
Add-Fix "atenci" "n" ("atenci" + [char]0x00F3 + "n")
Add-Fix "selecci" "n" ("selecci" + [char]0x00F3 + "n")
Add-Fix "Selecci" "n" ("Selecci" + [char]0x00F3 + "n")
Add-Fix "conexi" "n" ("conexi" + [char]0x00F3 + "n")
Add-Fix "Conexi" "n" ("Conexi" + [char]0x00F3 + "n")
Add-Fix "versi" "n" ("versi" + [char]0x00F3 + "n")
Add-Fix "Versi" "n" ("Versi" + [char]0x00F3 + "n")
Add-Fix "t" "tulo" ("t" + [char]0x00ED + "tulo")
Add-Fix "T" "tulo" ("T" + [char]0x00ED + "tulo")
Add-Fix "cr" "tico" ("cr" + [char]0x00ED + "tico")
Add-Fix "cr" "tica" ("cr" + [char]0x00ED + "tica")
Add-Fix "pr" "ximo" ("pr" + [char]0x00F3 + "ximo")
Add-Fix "pr" "xima" ("pr" + [char]0x00F3 + "xima")
Add-Fix "" "rea" ([char]0x00E1 + "rea")
Add-Fix "" "reas" ([char]0x00E1 + "reas")
Add-Fix "l" "nea" ("l" + [char]0x00ED + "nea")
Add-Fix "L" "nea" ("L" + [char]0x00ED + "nea")
Add-Fix "tama" "o" ("tama" + [char]0x00F1 + "o")
Add-Fix "Tama" "o" ("Tama" + [char]0x00F1 + "o")
Add-Fix "dise" "o" ("dise" + [char]0x00F1 + "o")
Add-Fix "Dise" "o" ("Dise" + [char]0x00F1 + "o")
Add-Fix "cach" "" ("cach" + [char]0x00E9)
Add-Fix "Cach" "" ("Cach" + [char]0x00E9)
Add-Fix "m" "x" ("m" + [char]0x00E1 + "x")
Add-Fix "m" "n" ("m" + [char]0x00ED + "n")
Add-Fix "m" "ximo" ("m" + [char]0x00E1 + "ximo")
Add-Fix "M" "ximo" ("M" + [char]0x00E1 + "ximo")
Add-Fix "m" "nimo" ("m" + [char]0x00ED + "nimo")
Add-Fix "M" "nimo" ("M" + [char]0x00ED + "nimo")
Add-Fix "" "ndice" ([char]0x00ED + "ndice")
Add-Fix "bot" "n" ("bot" + [char]0x00F3 + "n")
Add-Fix "Bot" "n" ("Bot" + [char]0x00F3 + "n")
Add-Fix "funci" "n" ("funci" + [char]0x00F3 + "n")
Add-Fix "Funci" "n" ("Funci" + [char]0x00F3 + "n")
Add-Fix "direcci" "n" ("direcci" + [char]0x00F3 + "n")
Add-Fix "Direcci" "n" ("Direcci" + [char]0x00F3 + "n")
Add-Fix "posici" "n" ("posici" + [char]0x00F3 + "n")
Add-Fix "Posici" "n" ("Posici" + [char]0x00F3 + "n")
Add-Fix "condici" "n" ("condici" + [char]0x00F3 + "n")
Add-Fix "edici" "n" ("edici" + [char]0x00F3 + "n")
Add-Fix "Edici" "n" ("Edici" + [char]0x00F3 + "n")
Add-Fix "relaci" "n" ("relaci" + [char]0x00F3 + "n")
Add-Fix "Relaci" "n" ("Relaci" + [char]0x00F3 + "n")
Add-Fix "soluci" "n" ("soluci" + [char]0x00F3 + "n")
Add-Fix "Soluci" "n" ("Soluci" + [char]0x00F3 + "n")
Add-Fix "organizaci" "n" ("organizaci" + [char]0x00F3 + "n")
Add-Fix "visualizaci" "n" ("visualizaci" + [char]0x00F3 + "n")
Add-Fix "actualizaci" "n" ("actualizaci" + [char]0x00F3 + "n")
Add-Fix "Actualizaci" "n" ("Actualizaci" + [char]0x00F3 + "n")
Add-Fix "verificaci" "n" ("verificaci" + [char]0x00F3 + "n")
Add-Fix "espec" "fico" ("espec" + [char]0x00ED + "fico")
Add-Fix "espec" "fica" ("espec" + [char]0x00ED + "fica")
Add-Fix "b" "sico" ("b" + [char]0x00E1 + "sico")
Add-Fix "B" "sico" ("B" + [char]0x00E1 + "sico")
Add-Fix "t" "cnico" ("t" + [char]0x00E9 + "cnico")
Add-Fix "T" "cnico" ("T" + [char]0x00E9 + "cnico")
Add-Fix "hist" "rico" ("hist" + [char]0x00F3 + "rico")
Add-Fix "Hist" "rico" ("Hist" + [char]0x00F3 + "rico")
Add-Fix "autom" "tico" ("autom" + [char]0x00E1 + "tico")
Add-Fix "Autom" "tico" ("Autom" + [char]0x00E1 + "tico")
Add-Fix "p" "blico" ("p" + [char]0x00FA + "blico")
Add-Fix "P" "blico" ("P" + [char]0x00FA + "blico")
Add-Fix "" "til" ([char]0x00FA + "til")
Add-Fix "f" "cil" ("f" + [char]0x00E1 + "cil")
Add-Fix "F" "cil" ("F" + [char]0x00E1 + "cil")
Add-Fix "an" "lisis" ("an" + [char]0x00E1 + "lisis")
Add-Fix "An" "lisis" ("An" + [char]0x00E1 + "lisis")
Add-Fix "m" "todo" ("m" + [char]0x00E9 + "todo")
Add-Fix "M" "todo" ("M" + [char]0x00E9 + "todo")
Add-Fix "par" "metro" ("par" + [char]0x00E1 + "metro")
Add-Fix "Par" "metro" ("Par" + [char]0x00E1 + "metro")
Add-Fix "di" "logo" ("di" + [char]0x00E1 + "logo")
Add-Fix "Di" "logo" ("Di" + [char]0x00E1 + "logo")
Add-Fix "c" "lculo" ("c" + [char]0x00E1 + "lculo")
Add-Fix "C" "lculo" ("C" + [char]0x00E1 + "lculo")
Add-Fix "v" "lido" ("v" + [char]0x00E1 + "lido")
Add-Fix "V" "lido" ("V" + [char]0x00E1 + "lido")
Add-Fix "v" "lida" ("v" + [char]0x00E1 + "lida")
Add-Fix "p" "rdida" ("p" + [char]0x00E9 + "rdida")
Add-Fix "l" "gica" ("l" + [char]0x00F3 + "gica")
Add-Fix "Buscar" "" ("Buscar" + $ellipsis)
Add-Fix "evaluador" "" ("evaluador" + $ellipsis)
Add-Fix "Actividad" "" ("Actividad" + $ellipsis)
Add-Fix "correlativo" "" ("correlativo" + $ellipsis)
Add-Fix "DNI" "" ("DNI" + $ellipsis)
Add-Fix "responsable)" "" ("responsable)" + $ellipsis)

$keys = @($explicit.Keys | Sort-Object { -$_.Length })
foreach ($k in $keys) {
  if ($k.Length -lt 2) { continue }
  $t = $t.Replace($k, $explicit[$k])
}

$t = $t.Replace(" $R ", " $middot ")
$t = $t.Replace(">$R<", ">$middot<")
$t = $t.Replace("0 $R 0", "0 $endash 0")
$t = $t.Replace("QBerries $R ", "QBerries $middot ")
$t = $t.Replace("INICIO $R ", "INICIO $middot ")
$t = $t.Replace("Fundos $R ", "Fundos $middot ")
$t = $t.Replace("Solo lectura $R ", "Solo lectura $middot ")
$t = $t.Replace("xls $R ", "xls $middot ")
$t = $t.Replace("valor $R ", "valor $middot ")
$t = $t.Replace("bruto $R neto", "bruto $middot neto")
$t = $t.Replace("9.6 $R 10.1 $R 10.6 $R 11.6 $R 12", "9.6 $middot 10.1 $middot 10.6 $middot 11.6 $middot 12")
$t = $t.Replace("Lugar $R ", "Lugar $middot ")
$mod = "m" + [char]0x00F3 + "dulo"
$Mod = "M" + [char]0x00F3 + "dulo"
$t = $t.Replace("$Mod $R ", "$Mod $middot ")
$t = $t.Replace("$mod $R ", "$mod $middot ")
$t = $t.Replace("cosecha $R escanear $R calidad", "cosecha $middot escanear $middot calidad")
$t = $t.Replace("supervisor $R cosecha", "supervisor $middot cosecha")
$t = $t.Replace([string]$R, [string]$middot)

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($indexPath, $t, $utf8)

$out = [System.IO.File]::ReadAllText($indexPath, $utf8)
$tamb = "Tambi" + [char]0x00E9 + "n"
$man = "ma" + [char]0x00F1 + "ana"
$dia = "d" + [char]0x00ED + "a"
$auto = "autom" + [char]0x00E1 + "ticamente"
$fffd = 0
foreach ($ch in $out.ToCharArray()) { if ($ch -eq [char]0xFFFD) { $fffd++ } }
Write-Host ("Tambien: " + $out.Contains($tamb))
Write-Host ("manana: " + $out.Contains($man))
Write-Host ("dia: " + $out.Contains($dia))
Write-Host ("automaticamente: " + $out.Contains($auto))
Write-Host ("modalLotesHoy: " + $out.Contains("modalLotesHoy"))
Write-Host ("Sup. General: " + $out.Contains("Sup. General"))
Write-Host ("FFFD left: " + $fffd)
